local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 70bc1ca7479b66754a1aa90814bbfe0b5bf5a62a3628436484099db0972ad2ab
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
